import {createClient} from 'npm:@supabase/supabase-js@2.57.4';
import {ImapFlow} from 'npm:imapflow@1.0.195';
import nodemailer from 'npm:nodemailer@7.0.10';
import MailComposer from 'npm:nodemailer@7.0.10/lib/mail-composer/index.js';
import {simpleParser} from 'npm:mailparser@3.7.4';
import {Buffer} from 'node:buffer';
import {encrypt,decrypt,resolveHost} from './security.mjs';
import {MAILBOXES,departmentsFor,parsePasswords,defaultCredentials,isDefaultEmail} from './departments.mjs';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
const headers={'Content-Type':'application/json','Cache-Control':'no-store'};
const json=(data:any,status=200)=>Response.json(data,{status,headers});
const check=(result:any)=>{if(result.error)throw Error('Database operation failed');return result.data};
const publicAccount=(a:any)=>({id:a.id,email:a.email,name:a.name});
const safeText=(s:any,max=10000)=>{if(typeof s!=='string'||s.length>max)throw Error('Invalid text field');return s};
async function encryptionKey(){const configured=Deno.env.get('MAIL_CREDENTIAL_KEY');if(configured){const key=Buffer.from(configured,'base64');if(key.length!==32)throw Error('Credential encryption key is invalid');return key}const {data,error}=await db.from('mail7mit_keys').select('secret').eq('id','credentials_v1').single();if(error||!data)throw Error('Credential encryption key has not been configured');const key=Buffer.from(data.secret,'base64');if(key.length!==32)throw Error('Credential encryption key is invalid');return key}
async function owner(body:any){if(!/^[a-f0-9-]{36}$/i.test(String(body.token||'')))throw Object.assign(Error('Sign in with akun.7mit'),{status:401});const s=check(await db.from('chat_user_sessions_v4').select('account_key,created_at').eq('token',body.token).eq('revoked',false).maybeSingle());if(!s)throw Object.assign(Error('Your session has ended. Sign in again.'),{status:401});const a=check(await db.from('portal_login_accounts').select('account_key,active').eq('account_key',s.account_key).eq('active',true).maybeSingle());if(!a)throw Object.assign(Error('Account is inactive'),{status:401});return s.account_key}
const passwords=()=>parsePasswords(Deno.env.get('MAIL_DEFAULT_MAILBOXES')||'');
let memberCache:any={at:0,rows:[]};
async function members(){if(Date.now()-memberCache.at<300000)return memberCache.rows;const roles=check(await db.from('organization_roles').select('id,role_key'));const byId=new Map(roles.map((r:any)=>[r.id,r.role_key]));const rows=check(await db.from('organization_members').select('role_id,role_key,member_name,student_name')).map((m:any)=>({role_key:m.role_key||byId.get(m.role_id),name:m.member_name||m.student_name}));memberCache={at:Date.now(),rows};return rows}
async function defaultKeys(user:string){const a=check(await db.from('portal_login_accounts').select('account_key,display_name,account_type,role').eq('account_key',user).eq('active',true).maybeSingle());if(!a)return[];let overrides={};try{overrides=JSON.parse(Deno.env.get('MAIL_DEPARTMENT_OVERRIDES')||'{}')}catch{/* ignore malformed override */}return departmentsFor(a,await members(),overrides)}
async function getAccount(id:string,user:string){if(id.startsWith('default:')){const key=id.slice(8);if(!(await defaultKeys(user)).includes(key))throw Object.assign(Error('Mailbox not found'),{status:404});const credentials=defaultCredentials(key,passwords());return{id,email:credentials.email,name:MAILBOXES[key as keyof typeof MAILBOXES].label,credentials,locked:true}}const a=check(await db.from('mail7mit_accounts').select('*').eq('id',id).eq('owner_id',user).maybeSingle());if(!a)throw Object.assign(Error('Mailbox not found'),{status:404});return{...a,credentials:decrypt(a.encrypted_credentials,await encryptionKey())}}
async function imap(credentials:any){const host=credentials.imapHost;const ip=await resolveHost(host);const client=new ImapFlow({host:ip,port:Number(credentials.imapPort),secure:credentials.imapTls==='ssl',doSTARTTLS:credentials.imapTls==='starttls',tls:{servername:host,rejectUnauthorized:true},auth:{user:credentials.imapUser,pass:credentials.imapPassword},logger:false,connectionTimeout:12000,greetingTimeout:12000,socketTimeout:30000,disableAutoIdle:true});await client.connect();return client}
async function smtp(c:any){const ip=await resolveHost(c.smtpHost);return nodemailer.createTransport({host:ip,port:Number(c.smtpPort),secure:c.smtpTls==='ssl',requireTLS:c.smtpTls==='starttls',tls:{servername:c.smtpHost,rejectUnauthorized:true},auth:{user:c.smtpUser,pass:c.smtpPassword},connectionTimeout:12000,greetingTimeout:12000,socketTimeout:30000,disableFileAccess:true,disableUrlAccess:true})}
function validateCredentials(v:any){if([25,587].includes(Number(v.smtpPort))){v.smtpPort=465;v.smtpTls='ssl';v.notice='This host blocks outgoing port 587, so SMTP uses TLS port 465 instead.'}for(const t of ['imap','smtp']){safeText(v[t+'Host'],253);safeText(v[t+'User'],320);safeText(v[t+'Password'],1000);const port=Number(v[t+'Port']);if(!Number.isInteger(port)||port<1||port>65535)throw Error('Invalid server port');if(!['ssl','starttls'].includes(v[t+'Tls']))throw Error('Encrypted connections are required');if([25,587].includes(port))throw Error('Supabase blocks ports 25 and 587. Use SMTP TLS port 465 or another supported provider port.')}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email))throw Error('Enter a valid email address');safeText(v.name,100);return v}
const summary=(m:any)=>({uid:m.uid,subject:m.envelope?.subject||'',from:(m.envelope?.from||[]).map((a:any)=>a.name?`${a.name} <${a.address}>`:a.address).join(', '),date:(m.internalDate||new Date()).toISOString(),seen:m.flags.has('\\Seen'),starred:m.flags.has('\\Flagged')});
async function getSource(client:any,uid:number){const m=await client.fetchOne(uid,{size:true,envelope:true,flags:true,internalDate:true},{uid:true});if(!m)throw Error('Message no longer exists');if(m.size>15*1024*1024)throw Error('This message is larger than the 15 MB viewer limit.');const src=await client.fetchOne(uid,{source:true},{uid:true});const parsed=await simpleParser(src.source,{skipHtmlToText:true,skipTextToHtml:true});return{m,parsed}}
async function action(body:any,user:string){
 if(body.action==='accounts'){const defaults=(await defaultKeys(user)).map(k=>({id:'default:'+k,email:MAILBOXES[k as keyof typeof MAILBOXES].email,name:MAILBOXES[k as keyof typeof MAILBOXES].label,locked:true}));return{accounts:[...defaults,...check(await db.from('mail7mit_accounts').select('id,email,name').eq('owner_id',user).order('created_at'))]}}
 if(body.action==='preferences'||body.action==='contacts'){const p=check(await db.from('mail7mit_preferences').select('signature,contacts').eq('owner_id',user).maybeSingle());return body.action==='contacts'?{contacts:p?.contacts||[]}:{signature:p?.signature||''}}
 if(body.action==='preferencesSave'||body.action==='contactsSave'){const change:any={owner_id:user,updated_at:new Date().toISOString()};if(body.action==='preferencesSave')change.signature=safeText(body.signature,5000);else{if(!Array.isArray(body.contacts)||body.contacts.length>500)throw Error('Maximum 500 contacts');change.contacts=body.contacts.map((c:any)=>({name:safeText(c.name,100),email:safeText(c.email,320)}))}check(await db.from('mail7mit_preferences').upsert(change,{onConflict:'owner_id'}));return{ok:true}}
 if(body.action==='addAccount'){if(Deno.env.get('MAIL_ALLOW_EXTERNAL')==='0')throw Object.assign(Error('Adding other mailboxes is disabled'),{status:403});const v=validateCredentials(body.values);if(isDefaultEmail(v.email)||isDefaultEmail(v.imapUser)||isDefaultEmail(v.smtpUser))throw Object.assign(Error('This is a default organization mailbox. Use the default entry in your mailbox list.'),{status:403});const client=await imap(v);try{const transport=await smtp(v);try{await transport.verify()}finally{transport.close()}}finally{await client.logout().catch(()=>client.close())}const {notice,...stored}=v;const encrypted_credentials=encrypt(stored,await encryptionKey());const a=check(await db.from('mail7mit_accounts').insert({owner_id:user,email:v.email,name:v.name,encrypted_credentials}).select('id,email,name').single());return{account:publicAccount(a),notice}}
 if(body.action==='deleteAccount'){if(String(body.account).startsWith('default:'))throw Object.assign(Error('Default mailboxes cannot be removed'),{status:403});check(await db.from('mail7mit_accounts').delete().eq('id',body.account).eq('owner_id',user));return{ok:true}}
 const a=await getAccount(body.account,user);const c=a.credentials;
 if(body.action==='send'||body.action==='draft'){
 const to=safeText(body.to||'',2000),subject=safeText(body.subject||'',998),message=safeText(body.body||'',1000000);if(/[\r\n]/.test(to+subject))throw Error('Invalid message header');if(!['text','html'].includes(body.format))throw Error('Invalid message format');
 if(!Array.isArray(body.attachments)||body.attachments.length>10)throw Error('Maximum 10 attachments');let bytes=0;const attachments=body.attachments.map((f:any)=>{const filename=safeText(f.filename,255).replace(/[\r\n/\\]/g,'_');const content=Buffer.from(safeText(f.content,14*1024*1024),'base64');bytes+=content.length;return{filename,content}});if(bytes>10*1024*1024)throw Error('Total attachments must be under 10 MB');
 const mail:any={from:{name:a.name,address:a.email},to,subject,attachments,disableFileAccess:true,disableUrlAccess:true};mail[body.format==='html'?'html':'text']=message;const compiled=new MailComposer(mail).compile();const raw=await new Promise<Buffer>((resolve,reject)=>compiled.build((e:any,b:Buffer)=>e?reject(e):resolve(b)));
 if(body.action==='send'){if(!to)throw Error('Recipient is required');const deliver=async(cfg:any)=>{const t=await smtp(cfg);try{await t.sendMail({envelope:compiled.getEnvelope(),raw,disableFileAccess:true,disableUrlAccess:true})}finally{t.close()}};try{await deliver(c)}catch(err:any){if(Number(c.smtpPort)===587&&/ETIMEDOUT|ECONNECTION|ECONNREFUSED|ESOCKET|EHOSTUNREACH|ENETUNREACH|timeout|blocked/i.test(String(err?.code||'')+' '+String(err?.message||''))){await deliver({...c,smtpPort:465,smtpTls:'ssl'})}else throw err}}
 let client;try{client=await imap(c);const folders=await client.list();const use=body.action==='draft'?'\\Drafts':'\\Sent';const destination=folders.find((f:any)=>f.specialUse===use)?.path||(body.action==='draft'?'Drafts':'Sent');if(!folders.some((f:any)=>f.path===destination))await client.mailboxCreate(destination);await client.append(destination,raw,body.action==='draft'?['\\Draft']:['\\Seen']);return{ok:true}}catch{if(body.action==='send')return{ok:true,warning:'Message was sent, but a copy could not be saved in Sent.'};throw Error('Draft could not be saved')}finally{if(client)await client.logout().catch(()=>client.close())}
 }
 const client=await imap(c);let lock;try{
 if(body.action==='folders'){const folders=await client.list();return{folders:folders.filter((f:any)=>!f.flags?.has('\\Noselect')).map((f:any)=>({path:f.path,name:f.name,specialUse:f.specialUse}))}}
 if(body.action==='createFolder'){await client.mailboxCreate(safeText(body.name,200));return{ok:true}}
 const folder=safeText(body.folder,500);lock=await client.getMailboxLock(folder);
 if(body.action==='messages'){const page=Math.max(0,Math.min(100000,Math.floor(Number(body.page)||0)));const query=safeText(body.query||'',200);const uids=await client.search(query?{text:query}:{all:true},{uid:true});uids.reverse();const chosen=uids.slice(page*25,page*25+25);const messages=[];if(chosen.length)for await(const m of client.fetch(chosen,{envelope:true,flags:true,internalDate:true},{uid:true}))messages.push(summary(m));messages.sort((a,b)=>b.uid-a.uid);const unseen=await client.search({seen:false},{uid:true});return{messages,total:uids.length,unread:unseen.length}}
 const uid=Number(body.uid);if(!Number.isSafeInteger(uid)||uid<1)throw Error('Invalid message ID');
 if(body.action==='flag'){if(!['read','star'].includes(body.flag)||typeof body.value!=='boolean')throw Error('Invalid flag');const flag=body.flag==='read'?'\\Seen':'\\Flagged';if(body.value)await client.messageFlagsAdd(uid,[flag],{uid:true});else await client.messageFlagsRemove(uid,[flag],{uid:true});return{ok:true}}
 if(body.action==='move'){await client.messageMove(uid,safeText(body.destination,500),{uid:true});return{ok:true}}
 if(body.action==='message'||body.action==='attachment'){const {m,parsed}=await getSource(client,uid);if(body.action==='attachment'){const index=Number(body.index);if(!Number.isInteger(index)||index<0||!parsed.attachments[index])throw Error('Attachment not found');const f=parsed.attachments[index];return{filename:f.filename||'attachment',content:f.content.toString('base64')}}await client.messageFlagsAdd(uid,['\\Seen'],{uid:true});const html=parsed.html?`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; font-src data:">${parsed.html}`:'';return{...summary(m),seen:true,text:parsed.text||'',html,attachments:parsed.attachments.map((f:any,index:number)=>({index,filename:f.filename||'attachment',size:f.size}))}}
 throw Error('Unknown mail action');
 }finally{if(lock)lock.release();await client.logout().catch(()=>client.close())}
}
Deno.serve(async req=>{if(req.method!=='POST')return json({error:'POST required'},405);if(Number(req.headers.get('content-length'))>16*1024*1024)return json({error:'Request too large'},413);try{const raw=await req.text();if(raw.length>16*1024*1024)return json({error:'Request too large'},413);const body=JSON.parse(raw);if(body.action==='status')return json({configured:true,backend:'Supabase Edge Functions',smtpBlockedPorts:[25,587],sync:'60-second polling'});if(body.action==='backgroundSync'){
 const secret=check(await db.from('mail7mit_sync_secret').select('secret').eq('id',true).single());
 if(!body.syncToken||body.syncToken!==secret?.secret)return json({error:'Unauthorized'},401);
 const accounts=check(await db.from('mail7mit_accounts').select('*').order('created_at').limit(500));
 const state=check(await db.from('mail7mit_sync_state').select('account_id,last_sync_at'));
 const times=new Map(state.map((x:any)=>[x.account_id,new Date(x.last_sync_at).getTime()]));
 accounts.sort((a:any,b:any)=>(times.get(a.id)||0)-(times.get(b.id)||0));
 const due=accounts.filter((a:any)=>Date.now()-(times.get(a.id)||0)>4*60000).slice(0,2);
 for(const a of due){let client;try{client=await imap(decrypt(a.encrypted_credentials,await encryptionKey()));const folders=await client.list();const lock=await client.getMailboxLock('INBOX');let snapshot;try{const total=client.mailbox.exists;const unread=await client.search({seen:false},{uid:true});const uids=await client.search({all:true},{uid:true});const selected=uids.slice(-50);const messages=[];if(selected.length)for await(const m of client.fetch(selected,{envelope:true,flags:true,internalDate:true},{uid:true}))messages.push(summary(m));snapshot={folders:folders.map((f:any)=>({path:f.path,name:f.name,specialUse:f.specialUse})),total,unread:unread.length,messages,uidValidity:String(client.mailbox.uidValidity)}}finally{lock.release()}check(await db.from('mail7mit_sync_state').upsert({account_id:a.id,last_sync_at:new Date().toISOString(),encrypted_snapshot:encrypt(snapshot,await encryptionKey()),error:null}))}catch{check(await db.from('mail7mit_sync_state').upsert({account_id:a.id,last_sync_at:new Date().toISOString(),error:'Mailbox sync failed'}))}finally{if(client)await client.logout().catch(()=>client.close())}}
 return json({synced:due.length});
 }
 const user=await owner(body);return json(await action(body,user))}catch(e:any){const status=e.status||400;const message=String(e.message||'Mail operation failed');return json({error:/pass|auth|login|credential|ENOTFOUND|ECONN|TLS|certificate/i.test(message)&&status!==401?'Mailbox connection failed. Check the server settings, credentials, and TLS certificate.':message.slice(0,300)},status)}});
