import {createCipheriv,createDecipheriv,randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
import {lookup} from 'node:dns/promises';
import {BlockList,isIP} from 'node:net';
export function encrypt(value,key){const iv=randomBytes(12);const c=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(JSON.stringify(value)),c.final(),c.getAuthTag()]).toString('base64')}
export function decrypt(value,key){const b=Buffer.from(value,'base64');const d=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(-16));return JSON.parse(Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString())}
export function verify(secret,user,timestamp,body,signature){if(!user||user.length>200||!/^[a-zA-Z0-9_-]+$/.test(user)||!/^\d+$/.test(timestamp)||Math.abs(Date.now()-Number(timestamp))>60000||!/^[a-f0-9]{64}$/.test(signature))return false;const expected=createHmac('sha256',secret).update(timestamp+'.'+user+'.'+body).digest();return timingSafeEqual(expected,Buffer.from(signature,'hex'))}
const blocked=new BlockList();const blockedV6=new BlockList();for(const [ip,prefix] of [['0.0.0.0',8],['10.0.0.0',8],['100.64.0.0',10],['127.0.0.0',8],['169.254.0.0',16],['172.16.0.0',12],['192.0.0.0',24],['192.168.0.0',16],['198.18.0.0',15],['224.0.0.0',4],['240.0.0.0',4]])blocked.addSubnet(ip,prefix,'ipv4');for(const [ip,prefix] of [['::',128],['::1',128],['fc00::',7],['fe80::',10],['ff00::',8],['::ffff:0:0',96],['2001:db8::',32],['2002::',16],['64:ff9b::',96]])blockedV6.addSubnet(ip,prefix,'ipv6');
export function publicAddress(address){const kind=isIP(address);return !!kind&&!(kind===4?blocked:blockedV6).check(address,kind===4?'ipv4':'ipv6')}
export async function resolveHost(host){if(typeof host!=='string'||host.length>253||! /^[a-zA-Z0-9.-]+$/.test(host)||host.includes('..')||!host.includes('.'))throw Error('Enter a public mail server hostname');const addresses=await lookup(host,{all:true});if(!addresses.length||addresses.some(a=>!publicAddress(a.address)))throw Error('Private or reserved mail server addresses are not allowed');return addresses[0].address}
