// Generates public/icons.js from the Lucide icon set (ISC license, https://lucide.dev). Run: node scripts/build-icons.mjs
import fs from 'node:fs';
const NAMES = ['mail', 'mail-open', 'mail-check', 'pen-line', 'inbox', 'file-pen', 'send', 'shield-ban', 'trash-2', 'archive', 'folder', 'folder-plus', 'search', 'search-x',
  'users', 'settings', 'star', 'paperclip', 'reply', 'reply-all', 'forward', 'chevron-left', 'menu', 'x', 'refresh-cw', 'check', 'sparkles', 'bold', 'italic', 'underline',
  'list', 'list-ordered', 'link', 'sun', 'moon', 'log-out', 'plus', 'folder-input', 'keyboard', 'image-off', 'file-text', 'file-spreadsheet', 'file-image', 'file', 'user-plus',
  'circle-alert', 'loader-circle', 'eye', 'at-sign', 'server', 'lock', 'bell', 'palette', 'signature', 'mail-plus', 'mail-question', 'arrow-left', 'trash', 'shield-check'];
const dir = 'node_modules/lucide-static/icons/';
const out = {};
for (const n of NAMES) {
  const f = dir + n + '.svg';
  if (!fs.existsSync(f)) { console.error('missing icon', n); process.exitCode = 1; continue; }
  out[n] = fs.readFileSync(f, 'utf8').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<!--[\s\S]*?-->/g, '').replace(/\s+/g, ' ').trim();
}
fs.writeFileSync('public/icons.js', `// Generated by scripts/build-icons.mjs from Lucide (ISC license). Do not edit by hand.
const ICONS = ${JSON.stringify(out)};
export function icon(name, size = 18, cls = '') {
  const t = document.createElement('template');
  t.innerHTML = '<svg class="ic ' + cls + '" width="' + size + '" height="' + size + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + (ICONS[name] || '') + '</svg>';
  return t.content.firstChild;
}
`);
console.log('icons:', Object.keys(out).length);
